### ISSUE TITLE
test_api ---- 'Dataset' object has no attribute 'remove_columns'

### ISSUE THREAD

**Issue by NicholasCao** [Hzfinfdu/PLMTuningCompetition#1]
调用示例的test.py报错
```py
Traceback (most recent call last):
  File "test.py", line 60, in <module>
    for res, _ in test_api(
  File "test_api.py", line 1066, in test_api
AttributeError: 'Dataset' object has no attribute 'remove_columns'
```

**Comment by NicholasCao** [comment]
windows test api

**Comment by Hzfinfdu** [comment]
我无法复现出这个错误，猜测可能的原因是datasets版本太老，我这里使用2.4.0. 如果仍然无法解决，请提供您在baseline代码基础上做的改动，我尝试帮您解决

**Comment by NicholasCao** [comment]
datasets==2.4.0可以成功解决，感谢。
